language: node_js
node_js:
  - "14"
deploy:
  provider: heroku
  api_key:
    secure: ubTYyI8OXawhmexk9/dx3i/PrUsF2DgSSZk7dRaJeyHjZzok2zzG75jipmu0/X/0xe99+mUKJq9jUncG0n5hAptteOx+Z12g9mc1aGTm/XBUvZ4Pbtr3P/5RNUX+9cisEjZkDVXRVRsiuEshwpgMnNcgv1WK8NW0gLwaMjFya0UqNZQ8Vmttk9TNeA9Nh3DkLhMkRejI8UgdvdMDGu9l7+N40SnzQDyU5HmmvqznXaUG5QNAmZiTLJc8CB6I0ODT4H1nTk5MGdcWOki8w+cLKzLXSHiWa54nTuIaKuzjRonEyPl4747olCLy375rnLSP3+EDNJhQkx+C5xUh6yxznKKn/2dZzc6P5wpbM1yCTNeQ2MOTqU5mzYkoKgzM3eVKjuih3MVJvBUTmF98nyq6tJoYHojLGTs2t0O39gyKAP7z2FbuVCh9KM7lmA1fG9J/fHB8ivHkK3+fsESlw8GH3cpJRvP7QQQq2SGBPrC3HuREn9UvYgzKCPOXsDEkh95LBXMWzNdKEZ1sVoGfQXnBdACmIGJNM0Fny8hJAymtbgEb4N7PMn/kFi8Xyt9099aF2n0gphmGMTqltPA8A5NWB3rOQ0Yl0bO5EtN7ujTU0j1M9Acjiq1z5vLXZivLn1JW4ZE9DmTEaawyhkwmydfAWTUfjQwcSO5Hg3o0cOr3lTw=
  app: se2-project-25